---
server:
  port: 8888
#security:
#  basic:
#    enabled: false
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/RuchiraGamage/SpringCloudConfig # default
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
          repos:
             perf:
                pattern: '*/perf'
                uri: https://github.com/RuchiraGamage/performanceTestConfig # alt
                search-paths:
                 - 'station*'
#  security:
##    basic:
##      enabled: true
#    user:
#      name: test
#      password: test


